config: disable KNI for 32-bit because cannot work
This is not supported, disable to avoid compilation error like:
	lib/librte_eal/linuxapp/kni/kni_misc.c:304:2: error:
		format '%llx' expects argument of type 'long long unsigned int',
		but argument 2 has type 'phys_addr_t' [-Werror=format]

Signed-off-by: Jean-Mickael Guerin <jean-mickael.guerin@6wind.com>
Acked-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>