eal/bsd: fix build
The i40e driver was using a #define value for the max number of rxtx interrupts
supported. This value was defined only for linux, giving an error when compiling
on FreeBSD.

  CC i40e_ethdev.o
/usr/home/bruce/dpdk.org/drivers/net/i40e/i40e_ethdev.c:3885:9: fatal error: use of undeclared
        identifier 'RTE_MAX_RXTX_INTR_VEC_ID'

Copying the necessary #define into the FreeBSD EAL header fixes the compile
error.

Fixes: d37641029ada ("eal/linux: add interrupt vectors")

Signed-off-by: Bruce Richardson <bruce.richardson@intel.com>