examples/distributor: fix build with icc 2015
examples/distributor/main.c(338): error #167:
	argument of type "struct rte_mbuf *"
	is incompatible with parameter of type "const char *"

The first param passed to _mm_prefetch is wrong,
need convert "struct rte_mbuf *" to "void *".

Fixes: 07db4a975094 ("examples/distributor: new sample app")

Signed-off-by: Michael Qiu <michael.qiu@intel.com>